on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@v1

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v1
      -
        name: Build and annotate policy
        uses: kubewarden/github-actions/policy-build-go@v1
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v1
        with:
          oci-target: ghcr.io/atoy3731/kubewarden-policies/istio
          tinygo-version: 0.20.0